[theme]
# Light theme configuration
primaryColor = "#007bff"          # Blue primary color
backgroundColor = "#ffffff"       # White background
secondaryBackgroundColor = "#f8f9fa"  # Light gray for sidebar/secondary elements
textColor = "#000000"            # Black text

[server]
# Optional: Set to false to prevent theme switching by users
enableStaticServing = false

[client]
# Optional: Show toolbar in deployed apps
toolbarMode = "auto" 